<?php
$list = 
array(
['name'=>__('Азербайджан', 'usam'), 'code'=>'AZ', 'currency'=>'AZN', 'numerical' => 031, 'phone_code' => 994, 'continent'=>'asiapacific'],
['name'=>__('Армения', 'usam'), 'code'=>'ARM', 'currency'=>'AMD', 'numerical' => 051, 'phone_code' => 374, 'continent'=>'asiapacific'],
['name'=>__('Россия', 'usam'), 'code'=>'RU', 'currency'=>'RUB', 'numerical' => 643, 'phone_code' => 7, 'continent'=>'europe'],
array('name'=>__('Молдавия', 'usam'), 'code'=>'MD', 'currency'=>'MDL', 'numerical' => 498, 'phone_code' => 373, 'continent'=>'europe'),
array('name'=>__('Мавритания', 'usam'), 'code'=>'MR', 'currency'=>'MRO', 'continent'=>'africa'),
array('name'=>__('Мартиника (Французская)', 'usam'), 'code'=>'MQ', 'currency'=>'EUR', 'continent'=>'southamerica'),
array('name'=>__('Мальта', 'usam'), 'code'=>'MT', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Маршалловы острова', 'usam'), 'code'=>'MH', 'currency'=>'USD', 'continent'=>'asiapacific'),
array('name'=>__('Мали', 'usam'), 'code'=>'ML', 'currency'=>'XOF', 'continent'=>'africa'),
array('name'=>__('Мальдивы', 'usam'), 'code'=>'MV', 'currency'=>'MVR', 'continent'=>'asiapacific'),
array('name'=>__('Малайзия', 'usam'), 'code'=>'MY', 'currency'=>'MYR', 'continent'=>'asiapacific'),
array('name'=>__('Малави', 'usam'), 'code'=>'MW', 'currency'=>'MWK', 'continent'=>'africa'),
array('name'=>__('Мадагаскар', 'usam'), 'code'=>'MG', 'currency'=>'MGA', 'continent'=>'africa'),
array('name'=>__('Макао', 'usam'), 'code'=>'MO', 'currency'=>'MOP', 'continent'=>'asiapacific' ),
array('name'=>__('Македония', 'usam'), 'code'=>'MK', 'currency'=>'MKD', 'continent'=>'europe'),
array('name'=>__('Люксембург', 'usam'), 'code'=>'LU', 'currency'=>'EUR', 'continent'=>'europe' ),
array('name'=>__('Литва', 'usam'), 'code'=>'LT', 'currency'=>'EUR', 'continent'=>'europe' ),
array('name'=>__('Лихтенштейн', 'usam'), 'code'=>'LI', 'currency'=>'CHF', 'continent'=>'europe'),
array('name'=>__('Ливия', 'usam'), 'code'=>'LY', 'currency'=>'LYD', 'continent'=>'africa' ),
array('name'=>__('Либерия', 'usam'), 'code'=>'LR', 'currency'=>'LRD', 'continent'=>'africa'),
array('name'=>__('Лесото', 'usam'), 'code'=>'LS', 'currency'=>'LSL', 'continent'=>'africa'),
array('name'=>__('Ливан', 'usam'), 'code'=>'LB', 'currency'=>'LBP', 'continent'=>'asiapacific'),
array('name'=>__('Латвия', 'usam'), 'code'=>'LV', 'currency'=>'LVL', 'continent'=>'europe'),
array('name'=>__('Лаос', 'usam'), 'code'=>'LA', 'currency'=>'LAK', 'continent'=>'asiapacific'),
array('name'=>__('Киргизия', 'usam'), 'code'=>'KG', 'currency'=>'KGS', 'numerical' => 417, 'phone_code' => 996, 'continent'=>'asiapacific'),
array('name'=>__('Южная Корея', 'usam'), 'code'=>'KR', 'currency'=>'KRW', 'continent'=>'asiapacific'),
array('name'=>__('Северная Корея', 'usam'), 'code'=>'KP', 'currency'=>'KPW', 'continent'=>'asiapacific'),
array('name'=>__('Кирибати', 'usam'), 'code'=>'KI', 'currency'=>'AUD', 'continent'=>'asiapacific'),
array('name'=>__('Кения', 'usam'), 'code'=>'KE', 'currency'=>'KES', 'continent'=>'africa'),
array('name'=>__('Казахстан', 'usam'), 'code'=>'KZ', 'currency'=>'KZT', 'numerical' => 398, 'phone_code' => 7, 'continent'=>'asiapacific'),	
array('name'=>__('Иордания', 'usam'), 'code'=>'JO', 'currency'=>'JOD', 'continent'=>'asiapacific'),
array('name'=>__('Джерси', 'usam'), 'code'=>'JE', 'currency'=>'GBP', 'continent'=>'europe'),
array('name'=>__('Япония', 'usam'), 'code'=>'JP', 'currency'=>'JPY', 'continent'=>'asiapacific'),
array('name'=>__('Ямайка', 'usam'), 'code'=>'JM', 'currency'=>'JMD', 'continent'=>'southamerica'),
array('name'=>__('Кот-д’Ивуар', 'usam'), 'code'=>'CI', 'currency'=>'XOF', 'continent'=>'africa'),
array('name'=>__('Италия', 'usam'), 'code'=>'IT', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Остров Мэн', 'usam'), 'code'=>'IM', 'currency'=>'GBP', 'continent'=>'europe'),
array('name'=>__('Израель', 'usam'), 'code'=>'IL', 'currency'=>'ILS', 'continent'=>'asiapacific'),
array('name'=>__('Ирландия', 'usam'), 'code'=>'IE', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Ирак', 'usam'), 'code'=>'IQ', 'currency'=>'IQD', 'continent'=>'asiapacific'),
array('name'=>__('Индонезия', 'usam'), 'code'=>'ID', 'currency'=>'IDR', 'continent'=>'asiapacific'),
array('name'=>__('Иран', 'usam'), 'code'=>'IR', 'currency'=>'IRR', 'continent'=>'asiapacific'),
array('name'=>__('Индия', 'usam'), 'code'=>'IN', 'currency'=>'INR', 'continent'=>'asiapacific'),
array('name'=>__('Исландия', 'usam'), 'code'=>'IS', 'currency'=>'ISK', 'continent'=>'europe'),
array('name'=>__('Венгрия', 'usam'), 'code'=>'HU', 'currency'=>'HUF', 'continent'=>'europe'),
array('name'=>__('Гондурас', 'usam'), 'code'=>'HN', 'currency'=>'HNL', 'continent'=>'southamerica'),
array('name'=>__('Острова Херд и Макдональд', 'usam'), 'code'=>'HM', 'currency'=>'AUD', 'continent'=>'asiapacific'),
array('name'=>__('Гаити', 'usam'), 'code'=>'HT', 'currency'=>'HTG', 'continent'=>'southamerica'),
array('name'=>__('Гайана', 'usam'), 'code'=>'GY', 'currency'=>'GYD', 'continent'=>'southamerica'),
array('name'=>__('Гвинея-Бисау', 'usam'), 'code'=>'GW', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Гвинея', 'usam'), 'code'=>'GN', 'currency'=>'GNF', 'continent'=>'africa'),
array('name'=>__('Гернси', 'usam'), 'code'=>'GG', 'currency'=>'GBP', 'continent'=>'europe'),
array('name'=>__('Гватемала', 'usam'), 'code'=>'GT', 'currency'=>'GTQ', 'continent'=>'southamerica'),
array('name'=>__('Гуам (США)', 'usam'), 'code'=>'GU', 'currency'=>'USD', 'continent'=>'asiapacific'),
array('name'=>__('Гренада', 'usam'), 'code'=>'GD', 'currency'=>'XCD', 'continent'=>'africa'),
array('name'=>__('Гваделупа (французская)', 'usam'), 'code'=>'GP', 'currency'=>'EUR', 'continent'=>'southamerica'),
array('name'=>__('Гренландия', 'usam'), 'code'=>'GL', 'currency'=>'DKK', 'continent'=>'europe'),
array('name'=>__('Греция', 'usam'), 'code'=>'GR', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Гибралтар', 'usam'), 'code'=>'GI', 'currency'=>'GIP', 'continent'=>'europe'),
array('name'=>__('Гана', 'usam'), 'code'=>'GH', 'currency'=>'GHS', 'continent'=>'africa'),
array('name'=>__('Германия', 'usam'), 'code'=>'DE', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Грузия', 'usam'), 'code'=>'GE', 'currency'=>'GEL', 'numerical' => 268, 'phone_code' => 995, 'continent'=>'europe'),
array('name'=>__('Гамбия', 'usam'), 'code'=>'GM', 'currency'=>'GMD', 'continent'=>'europe'),
array('name'=>__('Габон', 'usam'), 'code'=>'GA', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Южные французские территории', 'usam'), 'code'=>'TF', 'currency'=>'EUR', 'continent'=>'africa'),
array('name'=>__('Франция', 'usam'), 'code'=>'FR', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Финляндия', 'usam'), 'code'=>'FI', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Фиджи', 'usam'), 'code'=>'FJ', 'currency'=>'FJD', 'continent'=>'asiapacific'),
array('name'=>__('Фарерские острова', 'usam'), 'code'=>'FO', 'currency'=>'DKK', 'continent'=>'europe'),
array('name'=>__('Эфиопия', 'usam'), 'code'=>'ET', 'currency'=>'FKP', 'continent'=>'southamerica'),
array('name'=>__('Фолклендские острова', 'usam'), 'code'=>'FK', 'currency'=>'ETB', 'continent'=>'africa'),
array('name'=>__('Эстония', 'usam'), 'code'=>'EE', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Эритрея', 'usam'), 'code'=>'ER', 'currency'=>'ERN', 'continent'=>'africa'),
array('name'=>__('Экваториальная Гвинея', 'usam'), 'code'=>'GQ', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Сальвадор', 'usam'), 'code'=>'SV', 'currency'=>'USD', 'continent'=>'southamerica'),
array('name'=>__('Египет', 'usam'), 'code'=>'EG', 'currency'=>'EGP', 'continent'=>'africa'),
array('name'=>__('Эквадор', 'usam'), 'code'=>'EC', 'currency'=>'ECS', 'continent'=>'southamerica'),
array('name'=>__('Восточный Тимор', 'usam'), 'code'=>'TL', 'currency'=>'USD', 'continent'=>'asiapacific'),
array('name'=>__('Доминиканская республика', 'usam'), 'code'=>'DO', 'currency'=>'DOP', 'continent'=>'southamerica'),
array('name'=>__('Доминика', 'usam'), 'code'=>'DM', 'currency'=>'XCD', 'continent'=>'southamerica'),
array('name'=>__('Джибути', 'usam'), 'code'=>'DJ', 'currency'=>'DJF', 'continent'=>'africa'),
array('name'=>__('Дания', 'usam'), 'code'=>'DK', 'currency'=>'DKK', 'continent'=>'europe'),
array('name'=>__('Демократическая Республика Конго', 'usam'), 'code'=>'CD', 'currency'=>'CDF', 'continent'=>'africa'),
array('name'=>__('Чешская республика', 'usam'), 'code'=>'CZ', 'currency'=>'CZK', 'continent'=>'europe'),
array('name'=>__('Кипр', 'usam'), 'code'=>'CY', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Куба', 'usam'), 'code'=>'CU', 'currency'=>'CUP', 'continent'=>'northamerica'),
array('name'=>__('Хорватия', 'usam'), 'code'=>'HR', 'currency'=>'HRK', 'continent'=>'europe'),
array('name'=>__('Коста-Рика', 'usam'), 'code'=>'CR', 'currency'=>'CRC', 'continent'=>'southamerica'),
array('name'=>__('Острова Кука', 'usam'), 'code'=>'CK', 'currency'=>'NZD', 'continent'=>'asiapacific'),
array('name'=>__('Республика Конго', 'usam'), 'code'=>'CG', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Коморские острова', 'usam'), 'code'=>'KM', 'currency'=>'KMF', 'continent'=>'africa'),
array('name'=>__('Колумбия', 'usam'), 'code'=>'CO', 'currency'=>'COP', 'continent'=>'southamerica'),
array('name'=>__('Кокосовые острова', 'usam'), 'code'=>'CC', 'currency'=>'AUD', 'continent'=>'asiapacific'),
array('name'=>__('Остров Рождества', 'usam'), 'code'=>'CX', 'currency'=>'AUD', 'continent'=>'asiapacific'),
array('name'=>__('Чили', 'usam'), 'code'=>'CL', 'currency'=>'CLP', 'continent'=>'asiapacific'),
array('name'=>__('Китай', 'usam'), 'code'=>'CN', 'currency'=>'CHN', 'continent'=>'asiapacific'),
array('name'=>__('Чад', 'usam'), 'code'=>'TD', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Центрально-Африканская Республика', 'usam'), 'code'=>'CF', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Каймановы острова', 'usam'), 'code'=>'KY', 'currency'=>'KYD', 'continent'=>'northamerica'),
array('name'=>__('Кабо-Верде', 'usam'), 'code'=>'CV', 'currency'=>'CVE', 'continent'=>'africa'),
array('name'=>__('Камерун', 'usam'), 'code'=>'CM', 'currency'=>'XAF', 'continent'=>'africa'),
array('name'=>__('Канада', 'usam'), 'code'=>'CA', 'currency'=>'CAD', 'continent'=>'northamerica'),
array('name'=>__('Камбоджа', 'usam'), 'code'=>'KH', 'currency'=>'KHR', 'continent'=>'asiapacific'),
array('name'=>__('Бурунди', 'usam'), 'code'=>'BI', 'currency'=>'BIF', 'continent'=>'africa'),
array('name'=>__('Буркина-Фасо', 'usam'), 'code'=>'BF', 'currency'=>'XOF', 'continent'=>'africa'),
array('name'=>__('Болгария', 'usam'), 'code'=>'BG', 'currency'=>'BGL', 'continent'=>'europe'),
array('name'=>__('Бруней-Даруссалам', 'usam'), 'code'=>'BN', 'currency'=>'BND', 'continent'=>'asiapacific'),
array('name'=>__('Британская территория Индийского океана', 'usam'), 'code'=>'IO','currency'=>'USD', 'continent'=>'asiapacific'),
array('name'=>__('Бразилия', 'usam'), 'code'=>'BR', 'currency'=>'BRL', 'continent'=>'southamerica'),
array('name'=>__('Остров Буве', 'usam'), 'code'=>'BV', 'currency'=>'NOK', 'continent'=>'africa'),
array('name'=>__('Ботсвана', 'usam'), 'code'=>'BW', 'currency'=>'BWP', 'continent'=>'africa'),
array('name'=>__('Босния и Герцеговина', 'usam'), 'code'=>'BA', 'currency'=>'BAM', 'continent'=>'europe'),
array('name'=>__('Боливия', 'usam'), 'code'=>'BO', 'currency'=>'BOB', 'continent'=>'southamerica'),
array('name'=>__('Бутан', 'usam'), 'code'=>'BT', 'currency'=>'BTN', 'continent'=>'asiapacific'),
array('name'=>__('Бермудские острова', 'usam'), 'code'=>'BM', 'currency'=>'BMD', 'continent'=>'europe'),
array('name'=>__('Бенин', 'usam'), 'code'=>'BJ', 'currency'=>'XOF', 'continent'=>'africa'),
array('name'=>__('Белиз', 'usam'), 'code'=>'BZ', 'currency'=>'BZD', 'continent'=>'northamerica'),
array('name'=>__('Бельгия', 'usam'), 'code'=>'BE', 'currency'=>'EUR', 'continent'=>'europe'),
array('name'=>__('Беларусь', 'usam'), 'code'=>'BY', 'currency'=>'BYR', 'numerical' => 112, 'phone_code' => 375, 'continent'=>'europe'),
	['name'=>__('Украина', 'usam'), 'code'=>'UA', 'currency'=>'UKR', 'numerical' => 804, 'phone_code' => 380, 'continent'=>'europe'],
	['name'=>__('Узбекистан', 'usam'), 'code'=>'UZB', 'currency'=>'UZS', 'numerical' => 860, 'phone_code' => 998, 'continent'=>'europe'],
	['name'=>__('Таджикистан', 'usam'), 'code'=>'TJK', 'currency'=>'TJS', 'numerical' => 762, 'phone_code' => 992, 'continent'=>'europe'],
	['name'=>__('Туркменистан', 'usam'), 'code'=>'TKM', 'currency'=>'TMT', 'numerical' => 795, 'phone_code' => 993, 'continent'=>'europe'],	
	['name'=>__('Кыргызстан', 'usam'), 'code'=>'KGZ', 'currency'=>'KGS', 'numerical' => 417, 'phone_code' => 996, 'continent'=>'europe'],		
);