<?php
$list = 
array(
array('name'=>__('Российский рубль', 'usam'), 'symbol'=>'Ք', 'symbol_html'=>'&#8381;', 'code'=>'RUB', 'numerical'=>'643'),
array('name'=>__('Мавританская угия', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MRO', 'numerical'=>'478'),
array('name'=>__('Евро', 'usam'), 'symbol'=>'€', 'symbol_html'=>'&#8364;', 'code'=>'EUR', 'numerical'=>'978'),
array('name'=>__('Доллар США', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'USD', 'numerical'=>'840'),
array('name'=>__('Мальдивская руфия', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MVR', 'numerical'=>'462'),
array('name'=>__('Малайзийский ринггит', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MYR', 'numerical'=>'458'),
array('name'=>__('Малавийская квача', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MWK', 'numerical'=>'454'),
array('name'=>__('Малагасийский ариари', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MGA', 'numerical'=>''),
array('name'=>__('Патака Макао', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MOP', 'numerical'=>'' ),
array('name'=>__('Динар', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'MKD', 'numerical'=>''),
array('name'=>__('Швейцарский франк', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CHF', 'numerical'=>''),
array('name'=>__('Ливийский динар', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'LYD', 'numerical'=>'' ),
array('name'=>__('Либерийский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'LRD', 'numerical'=>''),
array('name'=>__('Лесото Лоти', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'LSL', 'numerical'=>''),
array('name'=>__('Ливанский фунт', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'LBP', 'numerical'=>''),
array('name'=>__('Латвийский лат', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'LVL', 'numerical'=>''),
array('name'=>__('Лаосский кип', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'LAK', 'numerical'=>''),
['name'=>__('Сом', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KGS', 'numerical'=> 417],
array('name'=>__('Корейская вона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KRW', 'numerical'=>''),
array('name'=>__('Северо-корейская вона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KPW', 'numerical'=>''),
array('name'=>__('Кенийский шиллинг', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KES', 'numerical'=>''),
array('name'=>__('Казахстанский тенге', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KZT', 'numerical'=>''),
array('name'=>__('Иорданский динар', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'JOD', 'numerical'=>''),
array('name'=>__('Фунт стерлингов', 'usam'), 'symbol'=>'£', 'symbol_html'=>'&#163;', 'code'=>'GBP', 'numerical'=>''),
array('name'=>__('Японская иена', 'usam'), 'symbol'=>'¥', 'symbol_html'=>'&#165;', 'code'=>'JPY', 'numerical'=>'392'),
array('name'=>__('Ямайский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'JMD', 'numerical'=>''),
array('name'=>__('Новый израильский шекель', 'usam'), 'symbol'=>'₪', 'symbol_html'=>'&#8362;', 'code'=>'ILS', 'numerical'=>''),
array('name'=>__('Иракский динар', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'IQD', 'numerical'=>''),
array('name'=>__('Индонезийская рупия', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'IDR', 'numerical'=>''),
array('name'=>__('Иранский риал', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'IRR', 'numerical'=>''),
array('name'=>__('Индийская рупия', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'INR', 'numerical'=>''),
array('name'=>__('Исландская крона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'ISK', 'numerical'=>''),
array('name'=>__('Венгерский форинт', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'HUF', 'numerical'=>''),
array('name'=>__('Гондурасская лемпира', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'HNL', 'numerical'=>''),
array('name'=>__('Австралийский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'AUD', 'numerical'=>''),
array('name'=>__('Гаитянский гурд', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'HTG', 'numerical'=>''),
array('name'=>__('Доллар гайаны', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'GYD', 'numerical'=>''),
array('name'=>__('Франк КФА BEAC', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'XAF', 'numerical'=>''),
array('name'=>__('Гвинейский франк', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GNF', 'numerical'=>''),
array('name'=>__('Гватемальский кетсаль', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GTQ', 'numerical'=>''),
array('name'=>__('Восточнокарибский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'XCD', 'numerical'=>''),
array('name'=>__('Гибралтарский фунт', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GIP', 'numerical'=>''),
array('name'=>__('Ганайские седи', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GHS', 'numerical'=>''),
array('name'=>__('Лари', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GEL', 'numerical'=>''),
array('name'=>__('Гамбийский даласи', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'GMD', 'numerical'=>''),
array('name'=>__('Доллар Фиджи', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'FJD', 'numerical'=>''),
array('name'=>__('Эфиопский бирр', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'FKP', 'numerical'=>''),
array('name'=>__('Фунт Фолклендских островов', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'ETB', 'numerical'=>''),
array('name'=>__('Эритрейская накфа', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'ERN', 'numerical'=>''),
array('name'=>__('Египетский фунт', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'EGP', 'numerical'=>''),
array('name'=>__('Эквадорский сукре', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'ECS', 'numerical'=>''),
array('name'=>__('Доминиканский песо', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'DOP', 'numerical'=>''),
array('name'=>__('Джибути', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'DJF', 'numerical'=>''),
array('name'=>__('Датская крона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'DKK', 'numerical'=>''),
array('name'=>__('Франк', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CDF', 'numerical'=>'976'),
array('name'=>__('Чешская крона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CZK', 'numerical'=>'203'),
array('name'=>__('Кубинское песо', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CUP', 'numerical'=>''),
array('name'=>__('Хорватская куна', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'HRK', 'numerical'=>''),
array('name'=>__('Коста-Риканский колон', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CRC', 'numerical'=>''),
array('name'=>__('Новозеландский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'NZD', 'numerical'=>''),
array('name'=>__('Франк Комор', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KMF', 'numerical'=>''),
array('name'=>__('Колумбийское песо', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'COP', 'numerical'=>''),
array('name'=>__('Чилийское песо', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CLP', 'numerical'=>''),
array('name'=>__('Китайский юань', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CNY', 'numerical'=>'156'),
array('name'=>__('Доллар Каймановых островов', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'KYD', 'numerical'=>''),
array('name'=>__('Эскудо Кабо-Верде', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'CVE', 'numerical'=>''),
array('name'=>__('Канадский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'CAD', 'numerical'=>''),
array('name'=>__('Риэль', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'KHR', 'numerical'=>''),
array('name'=>__('Бурундийский франк', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BIF', 'numerical'=>''),
array('name'=>__('Франк КФА BCEAO', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'XOF', 'numerical'=>''),
array('name'=>__('Болгарский лев', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BGL', 'numerical'=>''),
array('name'=>__('Брунейский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'BND', 'numerical'=>''),
array('name'=>__('Бразильский реал', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BRL', 'numerical'=>''),
array('name'=>__('Норвежская крона', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'NOK', 'numerical'=>''),
array('name'=>__('Ботсванская пула', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BWP', 'numerical'=>''),
array('name'=>__('Марка', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BAM', 'numerical'=>''),
array('name'=>__('Боливиано', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BOB', 'numerical'=>''),
array('name'=>__('Бутанский нгултрум', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BTN', 'numerical'=>''),
array('name'=>__('Бермудский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'BMD', 'numerical'=>''),
array('name'=>__('Белизский доллар', 'usam'), 'symbol'=>'$', 'symbol_html'=>'&#036;', 'code'=>'BZD', 'numerical'=>''),
array('name'=>__('Белорусский рубль', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'BYR', 'numerical'=>'933'),
array('name'=>__('Гривна', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'UAH', 'numerical'=>'980'),
array('name'=>__('Туркменский манат', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code'=>'TMT', 'numerical'=>'4217'),
array('name'=>__('Сомони', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code' => 'TJS', 'numerical' => '972'),
array('name'=>__('Узбекский сум', 'usam'), 'symbol'=>'', 'symbol_html'=>'', 'code' => 'UZS', 'numerical' => '860'),

);